#=
Scene 0 — "My First Scene"
Reverse-engineered from Radiance reference scene (Rendering with Radiance, Chapter 1).

A simple room with a light sphere, crystal ball, blue box, chrome rod,
glass window, exterior building, and ground plane.

Source files: scene0/scene0/{room.rad, window.rad, outside2.rad, sky.rad, default.vf}

Known limitations:
- genbox edge radius → sharp-edged box (Khepri box has no fillet parameter)
- Sky glow/ground glow → not modeled (use backend sky environment)
- Sun/brightfunc → not modeled (use backend sky environment)
=#

# Change this line to switch backends:
# using KhepriRadiance
# using KhepriMitsuba

## ─── Materials ─────────────────────────────────────────────────────────────

# Light source material: "void light bright 0 0 3 100 100 100"
# Emissive white — high energy light
bright_mat = standard_material(
  name="bright",
  base_color=rgba(1.0, 1.0, 1.0, 1.0),
  emissive=rgba(100.0, 100.0, 100.0, 1.0),
  data=BackendParameter(RAD => radiance_light_material("bright", red=100, green=100, blue=100)))

# Wall paint: "void plastic gray_paint 0 0 5 .5 .5 .5 0 0"
gray_paint_mat = standard_material(
  name="gray_paint",
  base_color=rgba(0.5, 0.5, 0.5, 1.0),
  roughness=1.0,
  data=BackendParameter(RAD => radiance_plastic_material("gray_paint", gray=0.5)))

# Crystal ball: "void dielectric crystal 0 0 5 .5 .5 .5 1.5 0"
crystal_mat = standard_material(
  name="crystal",
  base_color=rgba(0.5, 0.5, 0.5, 1.0),
  transmission=1.0,
  ior=1.5,
  roughness=0.0,
  data=BackendParameter(RAD => radiance_dielectric_material("crystal", gray=0.5)))

# Chrome rod: "void metal chrome 0 0 5 .8 .8 .8 .9 0"
chrome_mat = standard_material(
  name="chrome",
  base_color=rgba(0.8, 0.8, 0.8, 1.0),
  metallic=1.0,
  roughness=0.0,
  data=BackendParameter(RAD => radiance_metal_material("chrome", gray=0.8, specularity=0.9, roughness=0)))

# Blue box: "void plastic blue_plastic 0 0 5 .1 .1 .6 .05 .1"
blue_plastic_mat = standard_material(
  name="blue_plastic",
  base_color=rgba(0.1, 0.1, 0.6, 1.0),
  roughness=0.1,
  data=BackendParameter(RAD => radiance_plastic_material("blue_plastic", red=0.1, green=0.1, blue=0.6, specularity=0.05, roughness=0.1)))

# Floor: "void plastic brown 0 0 5 .2 .1 .1 0 0"
brown_mat = standard_material(
  name="brown",
  base_color=rgba(0.2, 0.1, 0.1, 1.0),
  roughness=1.0,
  data=BackendParameter(RAD => radiance_plastic_material("brown", red=0.2, green=0.1, blue=0.1)))

# Ceiling: "void plastic white 0 0 5 .7 .7 .7 0 0"
white_mat = standard_material(
  name="white",
  base_color=rgba(0.7, 0.7, 0.7, 1.0),
  roughness=1.0,
  data=BackendParameter(RAD => radiance_plastic_material("white", gray=0.7)))

# Window glass: "void glass window_glass 0 0 3 .96 .96 .96"
window_glass_mat = standard_material(
  name="window_glass",
  base_color=rgba(0.96, 0.96, 0.96, 0.3),
  transmission=0.96,
  ior=1.5,
  roughness=0.0,
  data=BackendParameter(RAD => radiance_glass_material("window_glass", gray=0.96)))

# Ground plane: "void plastic ground_mat 0 0 5 .28 .18 .12 0 0"
ground_mat = standard_material(
  name="ground_mat",
  base_color=rgba(0.28, 0.18, 0.12, 1.0),
  roughness=1.0,
  data=BackendParameter(RAD => radiance_plastic_material("ground_mat", red=0.28, green=0.18, blue=0.12)))

# Mirror building: "void mirror reflect20 0 0 3 .15 .2 .2"
# Radiance mirror type — approximate as highly reflective metal
reflect20_mat = standard_material(
  name="reflect20",
  base_color=rgba(0.15, 0.2, 0.2, 1.0),
  metallic=1.0,
  roughness=0.0,
  data=BackendParameter(RAD => RadianceMaterial("reflect20", "mirror", 0.15, 0.2, 0.2, nothing, nothing, nothing, nothing)))

## ─── Room geometry ─────────────────────────────────────────────────────────
# Room is 3m × 2m × 1.75m, origin at (0,0,0).
# Generated by: genbox gray_paint room 3 2 1.75 -i (inverted normals = interior)

# South wall (y=0 plane, inward-facing = normals toward +y)
# "gray_paint polygon room.1540": vertices at y=0
surface_polygon(
  xyz(0, 0, 0), xyz(0, 0, 1.75), xyz(3, 0, 1.75), xyz(3, 0, 0),
  material=gray_paint_mat)

# West wall (x=0 plane, inward-facing = normals toward +x)
# "gray_paint polygon room.4620": vertices at x=0
surface_polygon(
  xyz(0, 0, 0), xyz(0, 2, 0), xyz(0, 2, 1.75), xyz(0, 0, 1.75),
  material=gray_paint_mat)

# Floor (z=0 plane)
# "brown polygon room.2310": vertices at z=0
surface_polygon(
  xyz(0, 0, 0), xyz(3, 0, 0), xyz(3, 2, 0), xyz(0, 2, 0),
  material=brown_mat)

# North wall (y=2 plane, inward-facing = normals toward -y)
# "gray_paint polygon room.3267"
surface_polygon(
  xyz(3, 2, 1.75), xyz(0, 2, 1.75), xyz(0, 2, 0), xyz(3, 2, 0),
  material=gray_paint_mat)

# East wall (x=3 plane) with window opening (10 vertices polygon)
# "gray_paint polygon room.5137"
# The wall has a rectangular hole for the window at x=3,
# y=[0.625..1.375], z=[0.625..1.375]
surface_polygon(
  [xyz(3, 2, 1.75), xyz(3, 2, 0), xyz(3, 0, 0), xyz(3, 0, 1.75),
   xyz(3, 0.625, 1.75), xyz(3, 0.625, 0.625), xyz(3, 1.375, 0.625),
   xyz(3, 1.375, 1.375), xyz(3, 0.625, 1.375), xyz(3, 0.625, 1.75)],
  material=gray_paint_mat)

# Ceiling (z=1.75 plane)
# "white polygon room.6457"
surface_polygon(
  xyz(3, 2, 1.75), xyz(3, 0, 1.75), xyz(0, 0, 1.75), xyz(0, 2, 1.75),
  material=white_mat)

## ─── Window glass ──────────────────────────────────────────────────────────
# "window_glass polygon window" at x=3 plane
surface_polygon(
  xyz(3, 0.625, 1.375), xyz(3, 1.375, 1.375),
  xyz(3, 1.375, 0.625), xyz(3, 0.625, 0.625),
  material=window_glass_mat)

## ─── Light fixture ─────────────────────────────────────────────────────────
# "bright sphere fixture 0 0 4 2 1 1.5 .125"
sphere(xyz(2, 1, 1.5), 0.125, material=bright_mat)

## ─── Chrome rod (fixture support) ──────────────────────────────────────────
# "chrome cylinder fixture_support 0 0 7 2 1 1.5 2 1 1.75 .05"
cylinder(xyz(2, 1, 1.5), 0.05, xyz(2, 1, 1.75), material=chrome_mat)

## ─── Crystal ball ──────────────────────────────────────────────────────────
# "crystal sphere ball 0 0 4 .7 1.125 .625 .125"
sphere(xyz(0.7, 1.125, 0.625), 0.125, material=crystal_mat)

## ─── Blue box ──────────────────────────────────────────────────────────────
# "!genbox blue_plastic box .5 .5 .5 | xform -rz 15 -t .5 .75 0"
# 0.5×0.5×0.5 box, rotated 15° around z, then translated to (0.5, 0.75, 0)
# genbox edge radius not supported — sharp edges
box(loc_from_o_vx_vy(
      xyz(0.5, 0.75, 0),
      vxy(cos(deg2rad(15)), sin(deg2rad(15))),
      vxy(-sin(deg2rad(15)), cos(deg2rad(15)))),
    0.5, 0.5, 0.5,
    material=blue_plastic_mat)

## ─── Exterior: ground plane ────────────────────────────────────────────────
# "ground_mat ring groundplane 0 0 8 0 0 -.01 0 0 1 0 30"
# Annular ring at z=-0.01, inner_radius=0, outer_radius=30
surface_circle(xyz(0, 0, -0.01), 30, material=ground_mat)

## ─── Exterior: mirrored building ───────────────────────────────────────────
# "!genbox reflect20 building 10 10 2 | xform -t 10 5 0"
# 10×10×2 box translated to (10, 5, 0)
box(xyz(10, 5, 0), 10, 10, 2, material=reflect20_mat)

## ─── Camera ────────────────────────────────────────────────────────────────
# From default.vf: -vp 2.25 0.375 1 -vd -0.816497 0.408248 -0.408248 -vh 45 -vv 45
let vp = xyz(2.25, 0.375, 1.0),
    vd = vxyz(-0.816497, 0.408248, -0.408248)
  set_view(vp, vp + vd, lens=45)
end
